### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by shravan91** [Openahmedabad/openahmedabad.github.io#1]
@ndkcha or @jimishio can you please add _info@openahmedabad.org_ as the email ID on the main page of the website where anyone can send data or ask questions.

**Comment by ndkcha** [comment]
Should I add a button/link for it ?
- next to "Be The Part of The Community" section, next to "Discuss your ideas with us" button
- In "Have Something In Mind ?", right below github link

or any other suggestions ?

**Comment by shravan91** [comment]
Thanks for adding the feature @ndkcha @jimishio
